language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t OmarKYassin/docker-react -f Dockerfile.dockerfile .

script:
  - docker run -e CI=true OmarKYassin/docker-react npm run test